Repository doku-study/doku-study, pull requests merged in 2024-02, with the labels that each got.

#77 Chapter 9. Docker Container 배포하기 - Part I
  week07/kimchaejung/01-EC2-create-step.png
  week07/kimchaejung/02-amazon-linux-extras-problem.png
  week07/kimchaejung/03-amazon-linux-extras-solution-01.png
  week07/kimchaejung/04-docker-install-result.png
  week07/kimchaejung/05-inbound-rules.png
  week07/kimchaejung/kimchaejung.md
Labels: 수요일 스터디, 일요일 스터디

#74 Chapter 9. Docker Container 배포하기, 관리되는 컨테이너를 업데이트하기
  week07/simdongmin/images/browser-access.png
  week07/simdongmin/images/dockerhub.png
  week07/simdongmin/images/ec2-instance.png
  week07/simdongmin/images/ecs--options.png
  week07/simdongmin/images/ecs-running-cluster.png
  week07/simdongmin/images/ecs-running-cluster2.png
  week07/simdongmin/images/ecs-running-container-info.png
  week07/simdongmin/images/ecs-running-service-deploy.png
  week07/simdongmin/images/ecs-running-service.png
  week07/simdongmin/images/ecs-running-task-instance.png
  week07/simdongmin/images/ecs-running-task.png
  week07/simdongmin/images/ecs-service-cluster.png
  week07/simdongmin/images/ecs-service-update.png
  week07/simdongmin/images/ecs-service.png
  week07/simdongmin/images/ecs-task-container-env.png
  week07/simdongmin/images/ecs-task-container-setting-healthcheck.png
  week07/simdongmin/images/ecs-task-container-setting.png
  week07/simdongmin/images/ecs-task-container.png
  week07/simdongmin/images/ecs-task-infra.png
  week07/simdongmin/images/ecs-task.png
  week07/simdongmin/images/security-group-ssh-port.png
  week07/simdongmin/images/security-group-www-port.png
  week07/simdongmin/images/target-architecture.png
  week07/simdongmin/images/스크린샷 2024-01-30 오후 4.03.45.png
  week07/simdongmin/images/스크린샷 2024-01-30 오후 4.06.36.png
  week07/simdongmin/simdongmin.md
Labels: 수요일 스터디

#75 Chapter 9. Docker Container 배포하기 ~관리되는 컨테이너를 업데이트하기
  week07/kimjongjin.md
Labels: 수요일 스터디, 일요일 스터디

#78 Chapter 9. Docker Container 배포하기 - Part I
  week07/jungjunyoung.md
Labels: 일요일 스터디

#81 Chapter 9. Docker Container 배포하기 마무리
  week08/simdongmin/images/applyEfs.png
  week08/simdongmin/images/ec2.png
  week08/simdongmin/images/final.png
  week08/simdongmin/images/mongoDBDev.png
  week08/simdongmin/images/mongoDBProduct.png
  week08/simdongmin/images/multipleContainerApp.png
  week08/simdongmin/images/onlyEcs.png
  week08/simdongmin/simdongmin.md
Labels: 수요일 스터디

#82 Chapter 9. Docker Container 배포하기 - Part II
  week08/kimchaejung/01-node-EFS-architecture.png
  week08/kimchaejung/02-node-atlas-architecture.png
  week08/kimchaejung/03-final-architecture.png
  week08/kimchaejung/kimchaejung.md
Labels: 수요일 스터디, 일요일 스터디

#83 Chapter 10. Docker & 컨테이너 - 요약, Chapter 11. Kubernetes 시작하기
  week09/simdongmin/simdongmin.md
Labels: 수요일 스터디

#64 Chapter 6. Docker Compose: 우아한 다중 컨테이너 오케스트레이션, Chapter 7. “유틸리티 컨테이너로 작업하기 & 컨테이너에서 명령 실행하기
  .DS_Store
  env/docker_study.pem
  week05/jeonggyun.md
  week06/jeonggyun.md
  week09/jeonggyun.md
Labels: 일요일 스터디

#87 Chapter 10. Docker & 컨테이너 - 요약, Chapter 11. Kubernetes 시작하기
  week09/kimchaejung.md
Labels: 수요일 스터디, 일요일 스터디

#89 Chapter 10. Docker & 컨테이너 - 요약, Chapter 11. Kubernetes 시작하기
  week08/jungjunyoung.md
  week09/jungjunyoung.md
Labels: 일요일 스터디

#84 Chapter 10. Docker & 컨테이너 - 요약, Chapter 11. Kubernetes 시작하기
  week08/kimjongjin.md
  week09/kimjongjin.md
Labels: 수요일 스터디, 일요일 스터디

#90 Chapter 12. 실전 Kubernetes - 핵심 개념 자세히 알아보기 - Part I
  week10/kimchaejung/01_m1_command_not_working.png
  week10/kimchaejung/02_m1_hyperkit_not_working.png
  week10/kimchaejung/03_kubernetes_start.png
  week10/kimchaejung/04_image_pull_error.png
  week10/kimchaejung/05_double_table.png
  week10/kimchaejung/06_container_restart.png
  week10/kimchaejung/07_deployment_rollback.png
  week10/kimchaejung/kimchaejung.md
Labels: 수요일 스터디, 일요일 스터디

#94 Chapter 12. 실전 Kubernetes - 핵심 개념 자세히 알아보기 - Part I
  week10/jungjunyoung.md
Labels: 일요일 스터디
