Repository doku-study/doku-study, pull requests merged in 2024-01, with the labels that each got.

#16 chapter 1. 시작하기
  week01/dohun.md
Labels: 일요일 스터디

#19 chapter 2. Docker 이미지 & 컨테이너: 코어 빌딩 블록
  week02/simdongmin/cache-bust.png
  week02/simdongmin/dockerHubPractice.png
  week02/simdongmin/reordered-layers.png
  week02/simdongmin/simdongmin.md
  week03/simdongmiin/eval-volume.png
  week03/simdongmiin/image-security.png
  week03/simdongmiin/multiple-volume.png
  week03/simdongmiin/named-volume-practice.png
  week03/simdongmiin/named-volume.png
  week03/simdongmiin/readonly-volume.png
  week03/simdongmiin/simdongmin.md
  week03/simdongmiin/volume-practice1.png
  week03/simdongmiin/volume-practice2.png
  week03/simdongmiin/volume-practice3.png
  week03/simdongmiin/volume-practice4.png
  week03/simdongmiin/volume-practice5.png
  week03/simdongmiin/volume-practice6.png
  week03/simdongmiin/what-is-volume.png
Labels: 수요일 스터디

#22 chapter 2. Docker 이미지 & 컨테이너: 코어 빌딩 블록
  week02/seoyuri.md
Labels: 수요일 스터디

#18 chaper 2.Docker 이미지 & 컨테이너: 코어 빌딩 블록
  week02/seoseungmin.md
Labels: 수요일 스터디

#27 chaper 2.Docker 이미지 & 컨테이너: 코어 빌딩 블록
  .gitignore
  week02/kimsehyun/Part 1_Image와 container 간 관계.md
  week02/kimsehyun/Part 2_Image는 read-only file이다.md
  week02/kimsehyun/Part 3_Managing Images and Containers.md
  week02/kimsehyun/Part 4_Image 공유 - push, pull.md
  week02/kimsehyun/느낀 점.md
  week03/kimsehyun.md
Labels: 수요일 스터디

#31 chapter 3.데이터 관리 및 볼륨으로 작업하기
  week03/seoseungmin.md
Labels: 수요일 스터디

#28 chapter 3. 데이터 관리 및 볼륨으로 작업하기:폴더명 수정
  week03/simdongmin/eval-volume.png
  week03/simdongmin/image-security.png
  week03/simdongmin/multiple-volume.png
  week03/simdongmin/named-volume-practice.png
  week03/simdongmin/named-volume.png
  week03/simdongmin/readonly-volume.png
  week03/simdongmin/simdongmin.md
  week03/simdongmin/volume-practice1.png
  week03/simdongmin/volume-practice2.png
  week03/simdongmin/volume-practice3.png
  week03/simdongmin/volume-practice4.png
  week03/simdongmin/volume-practice5.png
  week03/simdongmin/volume-practice6.png
  week03/simdongmin/what-is-volume.png
Labels: 수요일 스터디

#29 chapter 3. 데이터 관리 및 볼륨으로 작업하기
  week03/seoyuri.md
Labels: 수요일 스터디

#25 chapter 2. Docker 이미지 & 컨테이너: 코어 빌딩 블록
  etc/youngin.md
  week02/youngin.md
Labels: 일요일 스터디

#14 chapter 1. 시작하기
  week01/README.md
  week01/SongMinhye.md
  week03/Ch3_data관리및볼륨.md
Labels: 일요일 스터디

#26 chapter 3. 데이터 관리 및 볼륨으로 작업하기
  week03/jungjunyoung.md
Labels: 일요일 스터디

#30 chapter 3. 데이터 관리 및 볼륨으로 작업하기
  README.md
  week03/kimchaejung.md
  weel05/README.md
  weel05/kimchaejung.md
Labels: 수요일 스터디, 일요일 스터디

#36 Chapter 3. 데이터 관리 및 볼륨으로 작업하기
  week03/kimsehyun/Part 1_Data와 Voume 이해하기.md
  week03/kimsehyun/Part 2_read-only 볼륨, 볼륨의 관리, dockerignore.md
Labels: 수요일 스터디

#21 week 2, 3, 4
  week02/leesubin.md
  week03/leesubin.md
  week04/leesubin.md
Labels: 수요일 스터디

#41 Chapter 3. 데이터 관리 및 볼륨으로 작업하기
  week03/yonghyeokrhee.md
Labels: 일요일 스터디

#43 chapter 4. 네트워킹: (교차) 컨테이너 통신, Docker로 다중 컨테이너 애플리케이션 구축하기
  week04/seoseungmin.md
Labels: 수요일 스터디

#42 Chapter 4. 네트워킹: (교차) 컨테이너 통신, Chapter 5. Docker로 다중 컨테이너 애플리케이션 구축하기
  week04/kimsehyun/section4.md
  week04/kimsehyun/section5.md
Labels: 수요일 스터디

#35 chapter 4. 네트워킹: (교차) 컨테이너 통신, chapter 5. Docker로 다중 컨테이너 애플리케이션 구축하기
  week04/seoyuri.md
Labels: 수요일 스터디

#34 chapter 3. 데이터 관리 및 볼륨으로 작업하기
  week03/kimjongjin.md
Labels: 일요일 스터디

#52 chapter 4.네트워킹: (교차) 컨테이너 통신
  week01/kimjinju.md
  week02/kimjinju.md
  week04/kimjinju.md
Labels: 일요일 스터디

#46 chapter 4. 네트워킹: (교차) 컨테이너 통신, chapter 5. Docker로 다중 컨테이너 애플리케이션 구축하기
  week04/kimchaejung.md
  week04/kimchaejung/error-log-01.png
  week04/kimchaejung/kimchaejung.md
Labels: 수요일 스터디, 일요일 스터디

#32 chapter 3.데이터 관리 및 볼륨으로 작업하기
  week02/kimjungin.md
  week03/kimjungin.md
Labels: 수요일 스터디

#48 Chapter 4. 네트워킹: (교차) 컨테이너 통신,Chapter 5. Docker로 다중 컨테이너 애플리케이션 구축하기
  week04/kimjongjin.md
Labels: 일요일 스터디

#51 chapter 4. 네트워킹: (교차) 컨테이너 통신
  .DS_Store
  week01/.DS_Store
  week02/.DS_Store
  week02/Image&Container.md
  week02/README.md
  week02/images/1.png
  week02/images/2.png
  week02/images/3.png
  week03/jeonggyun.md
  week04/jeonggyun/images/image_1.png
  week04/jeonggyun/images/image_2.png
  week04/jeonggyun/images/image_3.png
  week04/jeonggyun/images/image_4.png
  week04/jeonggyun/images/image_5.png
  week04/jeonggyun/images/image_6.png
  week04/jeonggyun/images/image_7.png
  week04/jeonggyun/jeonggyun.md
Labels: 일요일 스터디

#44 Chapter 4. 네트워킹: (교차) 컨테이너 통신, Chapter 5. Docker로 다중 컨테이너 애플리케이션 구축하기
  week04/simdongmin/containerIfconfig.png
  week04/simdongmin/networkInfo.png
  week04/simdongmin/pingTest.png
  week04/simdongmin/practice.png
  week04/simdongmin/simdongmin.md
Labels: 수요일 스터디

#37 chapter 3. 데이터 관리 및 볼륨으로 작업하기, chapter 4. 네트워킹: (교차) 컨테이너 통신, chapter 5. Docker로 다중 컨테이너 애플리케이션 구축하기
  etc/youngin.md
  week03/youngin.md
  week04/youngin.md
Labels: 일요일 스터디

#57 Chapter 6. Docker Compose: 우아한 다중 컨테이너 오케스트레이션, Chapter 7. “유틸리티 컨테이너"로 작업하기 & 컨테이너에서 명령 실행하기
  week05/seoyuri.md
Labels: 수요일 스터디

#59 chapter 6. Docker Compose: 우아한 다중 컨테이너 오케스트레이션, chapter 7. “유틸리티 컨테이너”로 작업하기 & 컨테이너에서 명령 실행하기
  week05/kimchaejung.md
Labels: 수요일 스터디, 일요일 스터디

#62 Chapter 6. Docker Compose: 우아한 다중 컨테이너 오케스트레이션, Chapter 7. “유틸리티 컨테이너로 작업하기 & 컨테이너에서 명령 실행하기
  week05/jungjunyoung.md
Labels: 일요일 스터디

#53 Chapter 6. Docker Compose: 우아한 다중 컨테이너 오케스트레이션, Chapter 7. “유틸리티 컨테이너…
  week05/kimsehyun/Sec6_Docker Compose_Elegant Multi-Container Orchestration.md
  week05/kimsehyun/Sec7_Working with Utility Containers Executing Commands in Containers.md
Labels: 일요일 스터디

#55 Chapter 6. Docker Compose: 우아한 다중 컨테이너 오케스트레이션, “유틸리티 컨테이너”로 작업하기 & 컨…
  week05/seoseungmin.md
Labels: 수요일 스터디

#56 Chapter 6. Docker Compose: 우아한 다중 컨테이너 오케스트레이션, Chapter 7. “유틸리티 컨테이너로 작업하기 & 컨테이너에서 명령 실행하기
  week05/kimjongjin.md
Labels: 수요일 스터디, 일요일 스터디

#54 Chapter 6. Docker Compose: 우아한 다중 컨테이너 오케스트레이션, Chapter 7. 유틸리티 컨테이너”…
  week05/simdongmin.md
Labels: 수요일 스터디

#70 Chapter 8. 더 복잡한 설정: Laravel & PHP 도커화 프로젝트
  week06/simdongmin.md
Labels: 수요일 스터디

#49 chapter 4.네트워킹: (교차) 컨테이너 통신
  week04/seulki.md
Labels: 일요일 스터디

#69 Chapter 8. 더 복잡한 설정: Laravel & PHP 도커화 프로젝트
  week06/kimchaejung.md
Labels: 수요일 스터디, 일요일 스터디

#67 Chapter 8.더 복잡한 설정: Laravel & PHP 도커화 프로젝트
  week06/kimsehyun.md
Labels: 수요일 스터디

#66 Chapter 8.더 복잡한 설정: Laravel & PHP 도커화 프로젝트
  week06/kimjongjin.md
Labels: 수요일 스터디, 일요일 스터디

#65 chapter 8.더 복잡한 설정: Laravel & PHP 도커화 프로젝트
  week06/seoseungmin.md
Labels: 수요일 스터디

#76 Chapter 9. Docker 컨테이너 배포하기 1
  week07/seoseungmin.md
Labels: 수요일 스터디
